language: python

install:
  - pip install pytest-cov
  - pip install python-coveralls

script: 
  - py.test coveralls/test_rpn.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing

after success:
  - coveralls